/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pokeball.glb 
Author: AtTheSpeedOf (https://sketchfab.com/AtTheSpeedOf)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/pokeball-acf58793b2d84551853c7d554866708d
Title: POKEBALL
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pokeball.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.button_low001_pokeball_0.geometry} material={materials.pokeball} position={[400, -9.755, -99.039]} scale={100} />
        <mesh geometry={nodes.button_low010_pokeball_0.geometry} material={materials.pokeball} position={[670, -9.755, -99.039]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.bottom_low001_pokeball_0.geometry} material={materials.pokeball} position={[400, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.bottom_low010_pokeball_0.geometry} material={materials.pokeball} position={[670, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/pokeball.glb')
