import { StatSpread } from "./types";

export interface MetaThreat {
  id: string;
  name: string;
  speciesName: string;
  role: string;
  types: string[];
  baseStats: StatSpread;
  level: number;
  evs: StatSpread;
  ivs: StatSpread;
  nature: string;
  item: string;
  ability: string;
  teraType?: string;
  formatTier: "OU" | "VGC" | "Ubers";
}

export const META_THREATS_LIST: MetaThreat[] = [
  {
    id: "great-tusk-def",
    name: "Great Tusk",
    speciesName: "great-tusk",
    role: "Physically Defensive Pivot / Spinner",
    types: ["ground", "fighting"],
    baseStats: { hp: 115, atk: 131, def: 131, spa: 53, spd: 53, spe: 87 },
    level: 100,
    evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
    ivs: { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31 },
    nature: "impish",
    item: "Leftovers",
    ability: "Protosynthesis",
    teraType: "Ice",
    formatTier: "OU",
  },
  {
    id: "ting-lu-spd",
    name: "Ting-Lu",
    speciesName: "ting-lu",
    role: "Specially Defensive Hazard Wall",
    types: ["dark", "ground"],
    baseStats: { hp: 155, atk: 110, def: 125, spa: 55, spd: 80, spe: 45 },
    level: 100,
    evs: { hp: 252, atk: 4, def: 0, spa: 0, spd: 252, spe: 0 },
    ivs: { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31 },
    nature: "careful",
    item: "Leftovers",
    ability: "Vessel of Ruin",
    teraType: "Poison",
    formatTier: "OU",
  },
  {
    id: "kingambit-bulky",
    name: "Kingambit",
    speciesName: "kingambit",
    role: "Supreme Overlord Endgame Sweeper",
    types: ["dark", "steel"],
    baseStats: { hp: 100, atk: 135, def: 120, spa: 60, spd: 85, spe: 50 },
    level: 100,
    evs: { hp: 212, atk: 252, def: 0, spa: 0, spd: 0, spe: 44 },
    ivs: { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31 },
    nature: "adamant",
    item: "Leftovers",
    ability: "Supreme Overlord",
    teraType: "Flying",
    formatTier: "OU",
  },
  {
    id: "gholdengo-specs",
    name: "Gholdengo",
    speciesName: "gholdengo",
    role: "Good as Gold Wallbreaker",
    types: ["steel", "ghost"],
    baseStats: { hp: 87, atk: 60, def: 95, spa: 133, spd: 91, spe: 84 },
    level: 100,
    evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 },
    ivs: { hp: 31, atk: 0, def: 31, spa: 31, spd: 31, spe: 31 },
    nature: "timid",
    item: "Choice Specs",
    ability: "Good as Gold",
    teraType: "Fighting",
    formatTier: "OU",
  },
  {
    id: "gliscor-stall",
    name: "Gliscor",
    speciesName: "gliscor",
    role: "Poison Heal Spikes / Protect",
    types: ["ground", "flying"],
    baseStats: { hp: 75, atk: 95, def: 125, spa: 45, spd: 75, spe: 95 },
    level: 100,
    evs: { hp: 244, atk: 0, def: 248, spa: 0, spd: 0, spe: 16 },
    ivs: { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31 },
    nature: "impish",
    item: "Toxic Orb",
    ability: "Poison Heal",
    teraType: "Water",
    formatTier: "OU",
  },
  {
    id: "dragonite-multiscale",
    name: "Dragonite",
    speciesName: "dragonite",
    role: "Multiscale Extreme Speed Sweeper",
    types: ["dragon", "flying"],
    baseStats: { hp: 91, atk: 134, def: 95, spa: 100, spd: 100, spe: 80 },
    level: 100,
    evs: { hp: 0, atk: 252, def: 4, spa: 0, spd: 0, spe: 252 },
    ivs: { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31 },
    nature: "adamant",
    item: "Heavy-Duty Boots",
    ability: "Multiscale",
    teraType: "Normal",
    formatTier: "OU",
  },
  {
    id: "incineroar-vgc",
    name: "Incineroar",
    speciesName: "incineroar",
    role: "VGC Intimidate / Parting Shot Anchor",
    types: ["fire", "dark"],
    baseStats: { hp: 95, atk: 115, def: 90, spa: 80, spd: 90, spe: 60 },
    level: 50,
    evs: { hp: 252, atk: 0, def: 156, spa: 0, spd: 100, spe: 0 },
    ivs: { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31 },
    nature: "impish",
    item: "Sitrus Berry",
    ability: "Intimidate",
    teraType: "Grass",
    formatTier: "VGC",
  },
  {
    id: "flutter-mane-vgc",
    name: "Flutter Mane",
    speciesName: "flutter-mane",
    role: "VGC Speed & Special Sweeper",
    types: ["ghost", "fairy"],
    baseStats: { hp: 55, atk: 55, def: 55, spa: 135, spd: 135, spe: 135 },
    level: 50,
    evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 },
    ivs: { hp: 31, atk: 0, def: 31, spa: 31, spd: 31, spe: 31 },
    nature: "timid",
    item: "Booster Energy",
    ability: "Protosynthesis",
    teraType: "Fairy",
    formatTier: "VGC",
  },
  {
    id: "urshifu-rapid-vgc",
    name: "Urshifu (Rapid Strike)",
    speciesName: "urshifu-rapid-strike",
    role: "Surging Strikes Wallbreaker",
    types: ["fighting", "water"],
    baseStats: { hp: 100, atk: 130, def: 100, spa: 63, spd: 60, spe: 97 },
    level: 50,
    evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 },
    ivs: { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31 },
    nature: "jolly",
    item: "Choice Scarf",
    ability: "Unseen Fist",
    teraType: "Water",
    formatTier: "VGC",
  },
  {
    id: "ogerpon-wellspring",
    name: "Ogerpon (Wellspring)",
    speciesName: "ogerpon-wellspring-mask",
    role: "Water Absorb Follow Me / Attacker",
    types: ["grass", "water"],
    baseStats: { hp: 80, atk: 120, def: 84, spa: 60, spd: 96, spe: 110 },
    level: 50,
    evs: { hp: 0, atk: 252, def: 4, spa: 0, spd: 0, spe: 252 },
    ivs: { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31 },
    nature: "jolly",
    item: "Wellspring Mask",
    ability: "Water Absorb",
    teraType: "Water",
    formatTier: "VGC",
  },
  {
    id: "landorus-therian",
    name: "Landorus-Therian",
    speciesName: "landorus-therian",
    role: "Intimidate Pivot / Stealth Rock",
    types: ["ground", "flying"],
    baseStats: { hp: 89, atk: 145, def: 90, spa: 105, spd: 80, spe: 91 },
    level: 100,
    evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
    ivs: { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31 },
    nature: "impish",
    item: "Rocky Helmet",
    ability: "Intimidate",
    teraType: "Water",
    formatTier: "OU",
  },
  {
    id: "dondozo-unaware",
    name: "Dondozo",
    speciesName: "dondozo",
    role: "Unaware Physical Sponge",
    types: ["water"],
    baseStats: { hp: 150, atk: 100, def: 115, spa: 65, spd: 65, spe: 35 },
    level: 100,
    evs: { hp: 252, atk: 0, def: 252, spa: 0, spd: 4, spe: 0 },
    ivs: { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31 },
    nature: "impish",
    item: "Leftovers",
    ability: "Unaware",
    teraType: "Grass",
    formatTier: "OU",
  },
];
